// your realisation of function AreMatricesIdentical for task 1
// your realisation of function AreMatricesIdentical for task 2
// your realisation of function AreMatricesIdentical for task 3
// your realisation of function AreMatricesIdentical for task 4
// your realisation of function AreMatricesIdentical for task 5
// your realisation of function AreMatricesIdentical for task 6
// your realisation of function AreMatricesIdentical for task 7
// your realisation of function AreMatricesIdentical for task 8
// your realisation of function AreMatricesIdentical for task 9
// your realisation of function AreMatricesIdentical for task 10
// your realisation of function AreMatricesIdentical for task 11